"""Generate CHANGELOG.md from the git gate tags (no network).

    python scripts/changelog.py [--repo .] [--out CHANGELOG.md]

One section per `*-gate` tag (newest first, tags in creation order), listing the commit subjects since the previous gate tag, plus an
"Unreleased" section for commits after the newest tag. Output depends only on the repository, so it is reproducible.
"""
import argparse
import subprocess
from pathlib import Path

HEADER = (
    "# Changelog\n\n"
    "Generated by `scripts/changelog.py` from the git gate tags. Do not edit by hand.\n"
    "A gate tag means the local gate passed; all rules are still DRAFT and not engineer-approved.\n"
)


def git(repo: Path, *args: str) -> str:
    return subprocess.run(["git", *args], cwd=repo, check=True, capture_output=True, text=True, encoding="utf-8").stdout


def gate_tags(repo: Path) -> list[tuple[str, str]]:
    """(tag, date) in creation order."""
    out = git(repo, "for-each-ref", "--sort=creatordate", "--format=%(refname:short)|%(creatordate:short)", "refs/tags/*-gate")
    return [(n, d) for n, d in (line.split("|", 1) for line in out.splitlines() if line)]


def subjects(repo: Path, rev_range: str) -> list[str]:
    return [s for s in git(repo, "log", "--format=%s", rev_range).splitlines() if s]


def section(title: str, items: list[str]) -> str:
    body = "\n".join(f"- {s}" for s in items) if items else "- (no commits)"
    return f"## {title}\n\n{body}\n"


def build(repo: Path) -> str:
    tags = gate_tags(repo)
    parts = [HEADER]
    if tags:
        parts.append(section("Unreleased", subjects(repo, f"{tags[-1][0]}..HEAD")))
    for i in range(len(tags) - 1, -1, -1):
        name, date = tags[i]
        rng = name if i == 0 else f"{tags[i - 1][0]}..{name}"
        parts.append(section(f"{name} ({date})", subjects(repo, rng)))
    if not tags:
        parts.append(section("Unreleased", subjects(repo, "HEAD")))
    return "\n".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--repo", default=".")
    ap.add_argument("--out", default="CHANGELOG.md")
    a = ap.parse_args()
    Path(a.out).write_text(build(Path(a.repo)), encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
