#!/usr/bin/env python3
"""Measure extraction accuracy per input type against fixtures with independently derived values; write the report.

  python scripts/ingest_accuracy.py            write docs/ingest-accuracy.md
  python scripts/ingest_accuracy.py --check    fail if the committed report is out of date

Numbers are measured, never targets. Each row says how many items were measured (n) and whether the fixtures are REAL
(public files from real programs) or SYNTHETIC (generated here). Input types with no fixtures are listed as NOT MEASURED.
"""
import math
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "apps" / "api"))
from mep.ingest.dxf import read_dxf
from mep.ingest.ifc import read_ifc

REPORT = ROOT / "docs" / "ingest-accuracy.md"
FIX = ROOT / "tests" / "fixtures" / "ifc"
AREA_TOLERANCE_M2 = 0.01


@dataclass
class Tally:
    n: int = 0
    ok: int = 0

    def add(self, good: bool) -> None:
        self.n += 1
        self.ok += bool(good)

    def pct(self) -> str:
        return "n/a" if self.n == 0 else f"{100 * self.ok / self.n:.1f}% ({self.ok}/{self.n})"


def ifc_rows() -> tuple[dict[str, Tally], list[str]]:
    expected = yaml.safe_load((FIX / "expected.yaml").read_text(encoding="utf-8"))
    tallies = {k: Tally() for k in ("spaces found (recall)", "no invented spaces (precision)", "GUID", "name",
                                    f"area within {AREA_TOLERANCE_M2} m2", "storey", "use")}
    files = []
    for name, want in expected.items():
        res = read_ifc(FIX / f"{name}.ifc")
        files.append(f"{name}.ifc")
        got = {s.key: s for s in res.spaces}
        for w in want["spaces"]:
            s = got.get(w["guid"])
            tallies["spaces found (recall)"].add(s is not None)
            tallies["GUID"].add(s is not None)
            tallies["name"].add(s is not None and s.name == w["name"])
            tallies[f"area within {AREA_TOLERANCE_M2} m2"].add(
                s is not None and s.area_m2 is not None and abs(s.area_m2 - w["area_m2"]) <= AREA_TOLERANCE_M2)
            tallies["storey"].add(s is not None and s.storey == w["storey"])
            tallies["use"].add(s is not None and s.use == w["use"])
        wanted = {w["guid"] for w in want["spaces"]}
        for key in got:
            tallies["no invented spaces (precision)"].add(key in wanted)
    return tallies, files


def dxf_rows() -> tuple[dict[str, Tally], list[str]]:
    """SYNTHETIC drawings with known polygons, in metres and in millimetres, with and without labels."""
    import ezdxf

    tallies = {k: Tally() for k in ("spaces found (recall)", f"area within {AREA_TOLERANCE_M2} m2", "name from label",
                                    "scale refused when units are missing")}
    cases = [("m", 6, 4, "Office", 6.0 * 4.0), ("mm", 5000, 3000, "Plant", 15.0), ("cm", 800, 500, "Store", 40.0)]
    with tempfile.TemporaryDirectory() as tmp:
        for units, w, h, label, area in cases:
            doc = ezdxf.new("R2018")
            doc.header["$INSUNITS"] = {"m": 6, "mm": 4, "cm": 5}[units]
            doc.layers.add("A-ROOM")
            msp = doc.modelspace()
            msp.add_lwpolyline([(0, 0), (w, 0), (w, h), (0, h)], close=True, dxfattribs={"layer": "A-ROOM"})
            msp.add_text(label, dxfattribs={"layer": "A-TEXT", "insert": (w / 2, h / 2)})
            path = Path(tmp) / f"{units}.dxf"
            doc.saveas(path)
            res = read_dxf(path)
            tallies["spaces found (recall)"].add(len(res.spaces) == 1)
            s = res.spaces[0] if res.spaces else None
            tallies[f"area within {AREA_TOLERANCE_M2} m2"].add(s is not None and s.area_m2 is not None
                                                               and math.isclose(s.area_m2, area, abs_tol=AREA_TOLERANCE_M2))
            tallies["name from label"].add(s is not None and s.name == label)
        doc = ezdxf.new("R2018")
        doc.header["$INSUNITS"] = 0          # ezdxf defaults new drawings to metres: make the units truly missing
        doc.layers.add("A-ROOM")
        doc.modelspace().add_lwpolyline([(0, 0), (6, 0), (6, 4), (0, 4)], close=True, dxfattribs={"layer": "A-ROOM"})
        doc.saveas(Path(tmp) / "none.dxf")
        res = read_dxf(Path(tmp) / "none.dxf")
        tallies["scale refused when units are missing"].add(res.spaces == [] and res.metadata["scale_ok"] is False)
    return tallies, [f"generated: {len(cases) + 1} drawings"]


def render() -> str:
    ifc, ifc_files = ifc_rows()
    dxf, dxf_files = dxf_rows()
    lines = [
        "# Extraction accuracy (measured)", "",
        ("Generated by `scripts/ingest_accuracy.py`; `--check` fails if this file is stale. Numbers are measured against "
        "values derived by hand from the fixtures, never targets. **Sample sizes are small**: read the n."), "",
        "## IFC (REAL files, public buildingSMART samples, one exporter: SketchUp)", "",
        f"Files: {', '.join(ifc_files)}. Ground truth: `tests/fixtures/ifc/expected.yaml` (derived from the STEP text).", "",
        "| Item | Accuracy |", "|---|---|"]
    lines += [f"| {k} | {v.pct()} |" for k, v in ifc.items()]
    lines += ["", ("Not measured: ceiling void (no fixture carries one); Revit and Archicad exports (none available; their "
              "profiles are `unverified`); real Australian project files."), "",
              "## DXF (SYNTHETIC drawings generated by the script)", "", f"Fixtures: {dxf_files[0]}.", "",
              "| Item | Accuracy |", "|---|---|"]
    lines += [f"| {k} | {v.pct()} |" for k, v in dxf.items()]
    lines += ["", "Synthetic drawings prove the reader's geometry and unit handling, not how real CAD exports behave.", "",
              "## PDF (vision)", "", ("**NOT MEASURED.** No vision model is wired and there are no PDF fixtures with known "
              "values. PDF output goes to the `extraction` table only, as `extracted`, and is never an engine input."), "",
              "## Excel schedule", "", ("Round-trip of the published templates is tested "
              "(`tests/ingest/test_schedule.py`). Accuracy of designers' own spreadsheets is **NOT MEASURED**."), "",
              "## What this does not show", "",
              "- No real project from the pilot firm has been read; all golden projects remain SYNTHETIC.",
              "- Extraction accuracy is not compliance accuracy: every extracted value is confirmed by a designer at Gate 1.", ""]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        if not REPORT.exists() or REPORT.read_text(encoding="utf-8").replace("\r\n", "\n") != text:
            print("docs/ingest-accuracy.md is out of date: run python scripts/ingest_accuracy.py", file=sys.stderr)
            return 1
        return 0
    REPORT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {REPORT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
